custom classification mode/bear detection mode
stefanodellosa-personal/WADAS pull request #101
Opened 2024-12-15 10:57 UTC by hexfati

First implementation of custom classification mode (in the specific case applied to "bear" animal, so "bear detection mode").
The class `CustomClassificationMode` inherits from `AnimalDetectionAndClassificationMode` because shares most of the code with it. The notification is sent only if a "bear" is identified.

2024-12-15 19:13 UTC, cdimauro commented on wadas/domain/animal_detection_mode.py
> +        if self.last_classified_animals_str:
Isn't this control redundant? I assume that the goal is to initialize / reset the last classification. So, the following line should be enough.

2024-12-15 19:13 UTC, cdimauro commented on wadas/domain/animal_detection_mode.py
> +                self.last_classified_animals_str = self.last_classified_animals_str + ", " + last
Maybe you can replace all this code with this (to be checked!):

self.last_classified_animals_str = ", ".join(animal["classification"][0] for animal in classified_animals)

2024-12-15 19:13 UTC, cdimauro commented on wadas/domain/animal_detection_mode.py
> +        if len(detection_results["detections"].xyxy) > 0:
if len(detection_results["detections"].xyxy):

or (but maybe with pandas or something like that doesn't work. Again, to be checked):

if detection_results["detections"].xyxy:

2024-12-15 19:13 UTC, cdimauro commented on wadas/domain/animal_detection_mode.py
> +                            message += f"animal from camera {cur_img['img_id']}!"
Can be combined in one line.

2024-12-15 19:13 UTC, cdimauro commented on wadas/domain/custom_classification_mode.py
> +                        message += f"animal from camera {cur_img['img_id']}!"
Same here.

2024-12-16 14:54 UTC, stefanodellosa-personal commented on wadas/domain/animal_detection_mode.py
> +    def _detect(self, cur_image_path):
I would say that _detect() method could be moved to generic class operation mode, as it is intent of WADAS to perform at least the animal detection.

2024-12-16 14:59 UTC, stefanodellosa-personal commented on wadas/domain/custom_classification_mode.py
> +                    self.update_image.emit(detected_img_path)
No, we don't update mainwindow with classification detail if classified animal differs from the target. We can only log that the classified animal is different from the target. We can report in log the classified animal but no action is taken in mainwindow.

2024-12-16 14:59 UTC, stefanodellosa-personal commented on wadas/domain/custom_classification_mode.py
> +                    if classified_img_path:
only if classified is target animal

2024-12-16 15:00 UTC, stefanodellosa-personal commented on wadas/domain/custom_classification_mode.py
> +                            logger.debug("Target animal '%s' not found", self.target_animal_label)
"Target animal %s not found, skipping notification."

2024-12-16 15:01 UTC, stefanodellosa-personal commented on wadas/domain/custom_classification_mode.py
> +                        logger.debug("No results to classify.")
"No animal to classify"

2024-12-16 15:03 UTC, stefanodellosa-personal commented on wadas/domain/custom_classification_mode.py
> +    def __init__(self, target_animal_label="bear"):
We have to check for target animal passed as parameter. it shall match with the list available in the model. (See wadas/ai/models.py list)

2024-12-16 15:04 UTC, stefanodellosa-personal requested changes
Please resolve comments before merge

2024-12-17 14:38 UTC, stefanodellosa-personal commented on wadas/domain/operation_mode.py
> +    def _initialize_process(self):
as we initialize multiple processes, perhaps name should be _initialize_processes()

2024-12-17 14:39 UTC, stefanodellosa-personal commented on wadas/domain/operation_mode.py
> +        # Initialize ai model
we actually do much more than simple Ai model init. please remove comment ad add proper docustring

2024-12-17 14:40 UTC, stefanodellosa-personal commented on wadas/domain/operation_mode.py
> +    def _initialize_cameras(self):
missing docustring

2024-12-17 14:40 UTC, stefanodellosa-personal commented on wadas/domain/operation_mode.py
> +    def _detect(self, cur_image_path):
missing docustring

2024-12-17 15:25 UTC, stefanodellosa-personal approved these changes

2024-12-17 15:44 UTC, merged